[program:mons_bot]
command=/root/mons_bot/venv/bin/python /root/mons_bot/main.py
directory=/root/mons_bot
user=root
autostart=true
autorestart=true
startretries=10
redirect_stderr=true
stdout_logfile=/var/log/mons_bot.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=PYTHONUNBUFFERED="1"
